spring:
  application:
    name: PairsChallengeConsumer

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: sia.pairschallenge.service.event.ProductEvent
        spring.json.value.default.type: sia.pairschallenge.service.event.ProductEvent
