
spring:
  application:
    name: PairsChallengeConsumer

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.use.type.headers: false
        #        spring.deserializer.value.delegate.class: sia.pairschallenge.mapper.ProductEventDeserializer
        spring.json.trusted.packages: sia.pairschallenge.service.event
        spring.json.value.default.type: sia.pairschallenge.event.ProductEvent2

server:
  port: 8081
